name: github pages

on:
  push:
    branches:
      - dev
    paths:
      - '*'
      - '!docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: build
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'
     
    - name: deploy-to-dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: dev
        PUBLISH_DOCS: docs
        PUBLISH_RESOURCE: resource
      run: |
        REPOSITORY_PATH="https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        cd .. && rm -rf $GITHUB_WORKSPACE/
        git clone $REPOSITORY_PATH && cd $GITHUB_WORKSPACE
        git checkout dev
        git config user.name "${GITHUB_ACTOR}";
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com";
        COMMIT_MESSAGE="Automated generate and deployment gitbook: $(date -u) ${GITHUB_SHA}"
        npm install gitbook-cli -g;
        gitbook install;
        gitbook build . $PUBLISH_DOCS;
        gitbook pdf . $PUBLISH_RESOURCE;
        git add -f $PUBLISH_DOCS;
        git add -f $PUBLISH_RESOURCE;
        git commit -m "${COMMIT_MESSAGE}"
        git push origin dev;
        # git checkout master;
        # git merge origin/dev;
        # git push --progress --porcelain origin refs/heads/master:master;
